action: log error

diff --git a/.github/workflows/formatting.yml b/.github/workflows/formatting.yml
--- a/.github/workflows/formatting.yml
+++ b/.github/workflows/formatting.yml
@@ -136,7 +136,8 @@ jobs:
           elif [ $rc -eq 1 ]; then
               # limit output as it might be a lot in the worst case
               tail -n 100 check_formatting_log.txt
-              echo "::warning ::Formatting is not following code style guide!"
+              echo "::error ::Formatting is not following code style guide!"
+              exit 1
           else
               cat check_formatting_log.txt
               # use last output line as error
